### ISSUE TITLE
compliance upload fails when processing dependencies of meta profiles

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2732]
## Describe the bug
_original issue: https://github.com/chef/customer-bugs/issues/27_
Specifically, it seems that when processing dependencies that are vendored with a meta profile, this can happen: method_missing': undefined method command' for #<#Class:0x00007fee6ae744c8:0x00007fee6ae87988> (NoMethodError)` 

## To Reproduce
Create base profile with a simple control like:
{code}
$ cat vendored/controls/example.rb
title "sample section"
describe command('ls') do
it {should exist}
end
{code}

Create meta profile including base profile as a dependency"
$ cat meta/inspec.yml
```
depends:

name: vendored
path: ../vendored
```
Attempt to upload:

```
$ inspec compliance upload meta

... giant stacktrace ...

     2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/profile_context.rb:161:in `instance_eval'
     1: from /Users/glass/.inspec/cache/00fd06747f4bb2fc79305c6c1da532347077f22e3c0a00e8e01501f8736365a0/controls/example.rb:6:in `load_with_context'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/dsl.rb:47:in method_missing': undefined method command' for #<#Class:0x00007fee6ae744c8:0x00007fee6ae87988> (NoMethodError)
```

## Expected behavior
Upload goes fine or tells me what i did wrong

## Additional context
My first guess is this would have gone fine had the profile been archived first, but that's just a guess. let's test/reproduce, then update with an appropriate msg if this is the case, or fix the broken if there's real breakage here

**Comment by vjeffrey** [comment]
note: the breakage/needed changes may actually be in inspec -- https://github.com/inspec/inspec/blob/master/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb#L129

**Comment by phiggins** [comment]
I can repro with the version of inspec mentioned in the zendesk ticket (4.7.18) but not with the latest version of inspec (4.18.51). This ticket looks like it is several months old, do we know if the customer can upgrade?

I've setup a simple profile structure with one profile depending on another:

```
Petes-MBP:profiles pete$ tree .
.
├── basic_profile
│   ├── controls
│   │   └── example.rb
│   └── inspec.yml
└── dependent_profile
    └── inspec.yml

3 directories, 3 files

Petes-MBP:profiles pete$ cat basic_profile/inspec.yml
name: basic_profile
title: About as simple a profile as possible
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: A simple profile
version: 0.1.0
Petes-MBP:profiles pete$ cat basic_profile/controls/example.rb
title "sample section"
describe command('ls') do
  it { should exist }
end
Petes-MBP:profiles pete$ cat dependent_profile/inspec.yml
name: dependent_profile
title: A profile that depends on another profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: A dependent profile
version: 0.1.0
depends:
  - name: basic_profile
    path: ../basic_profile
```

When I upload with 4.18.51:
```
Petes-MBP:profiles pete$ inspec compliance upload dependent_profile/
Dependencies for profile dependent_profile/ successfully vendored to /private/tmp/profiles/dependent_profile/vendor
I, [2020-02-05T10:47:41.086744 #37737]  INFO -- : Checking profile in dependent_profile/
I, [2020-02-05T10:47:41.087234 #37737]  INFO -- : Metadata OK.
W, [2020-02-05T10:47:41.092666 #37737]  WARN -- : No controls or tests were defined.
Profile is valid
Generate temporary profile archive at /var/folders/3d/kw7h7x0s39jdbhdyycl4jp_40000gn/T/dependent_profile20200205-37737-qlwncy.tar.gz
I, [2020-02-05T10:47:41.113100 #37737]  INFO -- : Generate archive /var/folders/3d/kw7h7x0s39jdbhdyycl4jp_40000gn/T/dependent_profile20200205-37737-qlwncy.tar.gz.
I, [2020-02-05T10:47:41.116024 #37737]  INFO -- : Finished archive generation.
Start upload to admin/dependent_profile
Uploading to Chef Automate
Successfully uploaded profile
```

When I upload with 4.7.18:
```
Petes-MBP:profiles pete$ inspec compliance upload dependent_profile/
Profile is already vendored. Use --overwrite.
I, [2020-02-05T10:50:39.020639 #37907]  INFO -- : Checking profile in dependent_profile/
I, [2020-02-05T10:50:39.021984 #37907]  INFO -- : Metadata OK.
Traceback (most recent call last):
        30: from /usr/local/lib/ruby/gems/2.6.0/bin/inspec:23:in `<main>'
        29: from /usr/local/lib/ruby/gems/2.6.0/bin/inspec:23:in `load'
        28: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-bin-4.7.18/bin/inspec:11:in `<top (required)>'
        27: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/base_cli.rb:33:in `start'
        26: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        21: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        20: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        19: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        18: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        17: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb:161:in `upload'
        16: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:411:in `check'
        15: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:441:in `controls_count'
        14: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:185:in `params'
        13: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:587:in `load_params'
        12: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:594:in `load_checks_params'
        11: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:192:in `collect_tests'
        10: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/dependencies/dependency_set.rb:63:in `each'
         9: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/dependencies/dependency_set.rb:63:in `each'
         8: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/dependencies/dependency_set.rb:64:in `block in each'
         7: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:194:in `collect_tests'
         6: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:194:in `each'
         5: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile.rb:198:in `block in collect_tests'
         4: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile_context.rb:145:in `load_control_file'
         3: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile_context.rb:161:in `load_with_context'
         2: from /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/profile_context.rb:161:in `instance_eval'
         1: from /Users/pete/.inspec/cache/fb50856bf3342d62c9a6e6fdcc95c35915a0991bf981dd4ee1db472a92c379fb/controls/example.rb:2:in `load_with_context'
/usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.7.18/lib/inspec/dsl.rb:47:in `method_missing': undefined method `command' for #<#<Class:0x00007f8ed9255b60>:0x00007f8ed92445e0> (NoMethodError)
```

I've attached a zip file of the profile structure used for future reference.
[profiles.zip](https://github.com/chef/automate/files/4161518/profiles.zip)

**Comment by vjeffrey** [comment]
thanks @phiggins -- this can be closed now!
