### ISSUE TITLE
windows ssm jobs silently failing

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#296]
# User Story

I can't seem to get any of the windows ssm jobs (aws or azure) to successfully send in a report to Automate.
I'm seeing a completed job with a report link, but no node shows up there. This has definitely worked in the past, so something is up.  The most recent change made to that script was for license acceptance; i have not tested if going back to a version .prior to that change makes a difference.
This was also reported by a customer.

# Definition of Done
Windows SSM jobs can send a report in to Automate.

# Demo Script / Repro Steps
get a publicly accessible Automate instance running in AWS.
Make sure there are a few nodes in AWS that are using the SSM role (there are some in the chef-engineering account already). 
Add an aws-ec2 no-creds integration.
Try to run an ssm job on linux machines, windows machines.
See if the report lands (I've seen it land for linux but not windows).
Create an Azure vm integration.
Run a scan job on those nodes, see if any of em land in Automate (I've seen it land for linux but not windows).

**Comment by vjeffrey** [comment]
looked into this a bit.
```
b:1252)
Traceback (most recent call last):
        16: from C:/opscode/inspec/bin/inspec:152:in `<main>'
        15: from C:/opscode/inspec/bin/inspec:152:in `load'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>
'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_c
ommand'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/cli.rb:269:in `exec'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:122:in `run'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:153:in `run_tests
'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `render_ou
tput'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `each'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:129:in `block in
render_output'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters.rb:37:in `render'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in
 `send_report'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in
 `to_json'
C:/opscode/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/reporters/automate.rb:41:in `encode': "\xC3"
 from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
PS C:\Users\Administrator> c

```
is the error i got from running this script:
```
$global:InspecBinaryLocation = "$env:systemdrive\opscode\inspec\bin\inspec"
				Function Invoke-InspecCommand {
						param(
								[Parameter(Mandatory=$false)]
								$Command = $null,
								[Parameter(Mandatory=$false)]
								$Path = $null,
								[Parameter(Mandatory=$false)]
								$JsonConfig
						)
						if($JsonConfig -ne $null) { $JsonArgument = '--json-config="-"' }
						Invoke-Expression -Command "echo '$JsonConfig' | $InspecBinaryLocation.bat $Command $Path $JsonArgument".Trim()
				}
				$env:CHEF_LICENSE="accept-no-persist"
				Invoke-InspecCommand -Command exec -Path "https://github.com/dev-sec/windows-baseline/archive/master.tar.gz" -JsonConfig '{"reporter":{"automate":{"url":"https://a2-url/data-collector/v0/","token":"token-val","node_uuid":"d02eda2f-b3f9-4ecd-9d62-7ee1017cdb5d","node_name":"test-node","environment":"test-env","report_uuid":"d02e78gh-b3f9-4ecd-9hb2-7ee8925cdb5d"}},"backend_cache":true}'
```
on a windows box..

**Comment by vjeffrey** [comment]
ok, so i tried with windows patch baseline since that was a formatting error. and it worked...so i think the real deal here is we need to:
1) make sure all the windows profiles are working well
2) figure out why an inspec exec that fails in that way does not get marked as a failure by the ssm job. 

if i echo $LastExitCode I get a 1, but if run $? I get a True...

**Comment by vjeffrey** [comment]
as far as i can tell we're getting back a success for those jobs: 
https://docs.aws.amazon.com/systems-manager/latest/userguide/monitor-commands.html
```
The command was received by SSM Agent on the instance and returned an exit code of zero. This status does not mean the command was successfully processed on the instance. This is a terminal state.
--
```

**Comment by vjeffrey** [comment]
following up, it looks like this is a known issue with powershell. so really the only thing that needs to happen is an update to the windows baseline profile.
i'll open a separate issue for that
