### ISSUE TITLE
The data feed service breaks when used with chef-load and compliance only data

### ISSUE THREAD

**Issue by srb3** [chef/automate#3954]
## Describe the bug
Discovered whilst running a chef-load test (https://github.com/chef/chef-load) configured to just send compliance data to chef automate.
The data feed service is enabled in the UI and configured to send to logstash. 
The chef-load program sends the compliance data to chef automate, however it also creates what appears to be an skeleton node entry in the infra tab for each compliance node that it reports.
It seems this 'bare bones' infra node causes the data feed service to crash

## To Reproduce
deploy automate
configure data feed service to report every 3m
enable data feed in the UI
set up chef load to send compliance data to automate
```
log_file = "/var/tmp/chef_load/chef-load.log"
data_collector_url = "https://chef-automate.test/data-collector/v0/"
data_collector_token = "rt+cGGX0Q+PNPg=="
compliance_status_json_file = "/var/tmp/chef_load/compliance_cloud_scan.json"
num_nodes = 7000
interval = 1440
node_name_prefix = "gcp-api"
num_actions = 30
```
once chef load is started, tail the logs on the automate server and grep for data-feed-service
you will see the following:

```
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Config file is /hab/svc/data-feed-service/config/config.toml"
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Starting Data Feed Service"
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Setting log level..." fields.level=info
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Database data_feed_service"
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Database connection string postgresql://admin:KMEsGZZ34TELBR6_@10.0.1.10
:10145/data_feed_service?sslmode=verify-ca&sslrootcert=/hab/svc/data-feed-service/config/_a2_platform_external_pg_root_ca.crt"
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Migration path /hab/pkgs/chef/data-feed-service/1.0.0/20200609183734/mig
rations"
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Running db migrations from \"/hab/pkgs/chef/data-feed-service/1.0.0/2020
0609183734/migrations\""
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Current schema version: 2" 
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Completed db migrations"
 data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="in initTables -- data-feed-service db "
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="completed initTables -- data-feed-service db "
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Starting data-feed-service"
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="creating workflow schedule" domain=data-feed-service enabled=true id=e119bcc7-8c94-458a-bb39-09e6eefa9056 instance_name=periodic-data-feed-workflow method=CreateWorkflowSchedule next_run_at="seconds:1592654610 " recurrence="FREQ=SECONDLY;DTSTART=20200620T120030Z;INTERVAL=180" workflow_n
ame=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=error msg="failed to create workflow schedule" domain=data-feed-service enabled=true 
error="workflow schedule already exists" id=e119bcc7-8c94-458a-bb39-09e6eefa9056 instance_name=periodic-data-feed-workflow method=CreateWorkflowSchedule next_run_at="seconds:1592654610 " recurrence="FREQ=SECONDLY
;DTSTART=20200620T120030Z;INTERVAL=180" workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="updating enabled" domain=data-feed-service id=061d5754-7ec4-457e-b50c-f3215b3ae77f instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="updating parameters" domain=data-feed-service id=061d5754-7ec4-457e-b50c-f3215b3ae77f instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="updating recurrence" domain=data-feed-service id=061d5754-7ec4-457e-b50c-f3215b3ae77f instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="updating workflow schedule" domain=data-feed-service id=061d5754-7ec4-457e-b50c-f3215b3ae77f instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Starting task poller" poll_interval="10s with up to 1s of jitter" task_name=data-feed-aggregate
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg=NewDatafeedServer
data-feed-service.default(O): time="2020-06-20T12:00:35Z" level=info msg="Starting task poller" poll_interval="10s with up to 1s of jitter" task_name=data-feed-poll
data-feed-service.default(HK): Health checking has been stopped
cereal-service.default(O): time="2020-06-20T12:03:30Z" level=warning msg="Scheduled workflow \"periodic-data-feed-workflow\" still running, consider increasing recurrence interval"
cereal-service.default(O): time="2020-06-20T12:09:30Z" level=warning msg="Scheduled workflow \"periodic-data-feed-workflow\" still running, consider increasing recurrence interval"
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="Building report feed... 2020-06-20T12:15:00Z - 2020-06-20T12:18:00Z"
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="updating enabled" domain=data-feed-service id=ddcd6a6f-52a4-4ed9-9de2-ccf93a0c1c0d instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="updating parameters" domain=data-feed-service id=ddcd6a6f-52a4-4ed9-9de2-ccf93a0c1c0d instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="updating workflow schedule" domain=data-feed-service id=ddcd6a6f-52a4-4ed9-9de2-ccf93a0c1c0d instance_name=periodic-data-feed-workflow method=UpdateWorkflowScheduleByName workflow_name=data-feed-workflow
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="Building data feed..."
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=error msg="Error getting cfgmgmt/nodes rpc error: code = InvalidArgument desc = Invalid filter (format: key:value) ipaddress:"
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=warning msg="Error getting node macaddress and hostname rpc error: code = InvalidArgument desc = Invalid filter (format: key:value) ipaddress:"
data-feed-service.default(O): panic: interface conversion: interface {} is nil, not string
data-feed-service.default(O):
data-feed-service.default(O): goroutine 1359 [running]:
data-feed-service.default(O): github.com/chef/automate/components/data-feed-service/service.getHostAttributes(...)
data-feed-service.default(O):         /src/components/data-feed-service/service/data-feed-service.go:324
data-feed-service.default(O): github.com/chef/automate/components/data-feed-service/service.getNodeData(0xe7c8e0, 0xc0000af1c0, 0xe89ae0, 0xc0000417e0, 0xc0003537e0, 0x1, 0x1, 0x40c614, 0xc0002ee5e0, 0x20)
data-feed-service.default(O):         /src/components/data-feed-service/service/data-feed-service.go:225 +0x87d
data-feed-service.default(O): github.com/chef/automate/components/data-feed-service/service.(*DataFeedAggregateTask).getNodeClientData(0xc000030c40, 0xe7c8e0, 0xc0000af1c0, 0xc0001da550, 0xf, 0xc000128b70, 0x24, 0x0, 0x0, 0xc0000af201, ...)
data-feed-service.default(O):         /src/components/data-feed-service/service/data-feed-aggregate-task.go:149 +0x1f0
data-feed-service.default(O): github.com/chef/automate/components/data-feed-service/service.(*DataFeedAggregateTask).buildDatafeed(0xc000030c40, 0xe7c8e0, 0xc0000af1c0, 0xc0002d8150, 0xc000105101, 0x1, 0x1, 0x30)
data-feed-service.default(O):         /src/components/data-feed-service/service/data-feed-aggregate-task.go:116 +0x346
data-feed-service.default(O): github.com/chef/automate/components/data-feed-service/service.(*DataFeedAggregateTask).Run(0xc000030c40, 0xe7c8e0, 0xc0000af1c0, 0xe6b820, 0xc0000af180, 0xc0003175f8, 0x45d337, 0xc002a0, 0x0)
data-feed-service.default(O):         /src/components/data-feed-service/service/data-feed-aggregate-task.go:57 +0x156
data-feed-service.default(O): github.com/chef/automate/lib/cereal.(*registeredExecutor).runTask(0xc000071e00, 0xe7c8e0, 0xc0000af1c0, 0xc0000af180, 0xe77aa0, 0xc0002d80c0, 0x1, 0xc0002d80c0)
data-feed-service.default(O):         /src/lib/cereal/cereal.go:938 +0xaa
data-feed-service.default(O): github.com/chef/automate/lib/cereal.(*registeredExecutor).startTaskWorker.func1(0xc000100000, 0xe62e40, 0xc0003d45b0, 0xe7c8e0, 0xc0000ae400, 0xc000071e00, 0xc0004ec160)
data-feed-service.default(O):         /src/lib/cereal/cereal.go:929 +0xdb
data-feed-service.default(O): created by github.com/chef/automate/lib/cereal.(*registeredExecutor).startTaskWorker
data-feed-service.default(O):         /src/lib/cereal/cereal.go:900 +0x298
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=error msg="failed to get task completion message" domain=data-feed-service error="context canceled" id=beed6372-ce5b-4a10-a744-2766864ad440 method=DequeueTask task_name=data-feed-aggregate
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="sending task cancellation message" domain=data-feed-service error="context canceled" id=beed6372-ce5b-4a10-a744-2766864ad440 method=DequeueTask task_name=data-feed-aggregate
cereal-service.default(O): time="2020-06-20T12:18:30Z" level=error msg="failed to send task cancellation message" domain=data-feed-service error="context canceled" id=beed6372-ce5b-4a10-a744-2766864ad440 method=DequeueTask task_name=data-feed-aggregate
hab-launch(SV): Child for service 'data-feed-service.default' with PID 32261 exited with code exit code: 2
```
most relevant parts seem to be:
```
ata-feed-service.default(O): time="2020-06-20T12:18:30Z" level=info msg="Building data feed..."
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=error msg="Error getting cfgmgmt/nodes rpc error: code = InvalidArgument desc = Invalid filter (format: key:value) ipaddress:"
data-feed-service.default(O): time="2020-06-20T12:18:30Z" level=warning msg="Error getting node macaddress and hostname rpc error: code = InvalidArgument desc = Invalid filter (format: key:value) ipaddress:"
data-feed-service.default(O): panic: interface conversion: interface {} is nil, not string
```
In the screenshots attached for the infra node attributes there is no mac address. So my guess is that the badly structured chef-load node object is causing the issue, I decided to raise this issue here so as I think we would want to handle this kind of unexpected node data than to let the data-feed service crash.

## Expected behavior
The data feed service sends all compliance data to the designated endpoint (logstash in my case)

## Screenshots
![Selection_249](https://user-images.githubusercontent.com/28541829/85208892-be8b7e80-b32b-11ea-8b86-b4f30d57df22.png)
![Selection_250](https://user-images.githubusercontent.com/28541829/85208896-c2b79c00-b32b-11ea-9774-af80c1d366f0.png)
![Selection_252](https://user-images.githubusercontent.com/28541829/85208899-c6e3b980-b32b-11ea-91de-f878c2e8355b.png)
![Selection_251](https://user-images.githubusercontent.com/28541829/85208902-c9deaa00-b32b-11ea-8643-1bb2b00a2cab.png)
![Selection_253](https://user-images.githubusercontent.com/28541829/85208940-0a3e2800-b32c-11ea-9511-20b4740fc463.png)

## Versions (please complete the following information):
- OS: CentOS 7
- Browser Chrome
- Automate Build Number: 20200610173731

**Comment by satellite15** [comment]
@srb3 I was able to reproduce this with a unit test and have added some nil checks (and unit tests) for this scenario to the code in this branch 

https://github.com/chef/automate/tree/satellite15/%233954

If this works for your environment I'll open a PR
