### ISSUE TITLE
Protractor test runner has "unknown error" when run locally(front-end)

### ISSUE THREAD

**Issue by msorens** [chef/automate#4702]
## Describe the issue
The end-to-end test runner Protractor is reporting an "unknown error" when run locally.
It seems to be working fine from Buildkite (example: https://buildkite.com/chef-oss/chef-automate-master-verify/builds/14815#190ba674-3368-4d16-9809-5f26b65b2b10)

## To Reproduce
From components/automate-ui run `make e2e` and this error appears:
```
[09:18:18] I/launcher - Running 1 instances of WebDriver
[09:18:18] I/direct - Using ChromeDriver directly...
[09:18:19] E/launcher - spawn Unknown system error -86
[09:18:19] E/launcher - Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:540:9)
    at exec (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/selenium-webdriver/io/exec.js:116:27)
    at /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/selenium-webdriver/remote/index.js:219:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/built/runner.js:195:43)
    at /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/protractor/node_modules/q/q.js:137:13)```

References that will help with this:
-  https://stackoverflow.com/questions/65618558/osx-fix-selenium-chromedriver-launch-error-spawn-unknown-system-error-86-bad-cp
-  https://github.com/angular/webdriver-manager/issues/476

## Expected behavior
No error.

**Comment by SEAjamieD** [comment]
This is really putting a damper on testing efforts so i'm bumping its importance up
