### ISSUE TITLE
Performance testing of automate infra views and service.

### ISSUE THREAD

**Issue by vsingh-msys** [chef/automate#4775]
### User Story

- Automate infra views need to validates tone of data set of cookbooks, roles, data bags, environments and clients.
- In order to load the nodes data throughout the automate lib http://github.com/chef/chef-load is used.
- Enhancing the chef-load to support loading all chef server data could be possible for out of scope for now.
- Either way we can think of providing these data set support to https://github.com/chef/automate/tree/master/components/sample-data-service service as well.
- Integration tests for infra-proxy-service could be another way of loading the data set.

**Comment by kagarmoe** [comment]
The @chef/docs-team strongly supports improving the Automate test data. We use test data in our images. Screenshots of Automate with meaningful data both advertises its features and gives our customers useful examples.

**Comment by vsingh-msys** [comment]
- Thinking of providing hab command `infra_service_load_test_data INFRA_SERVER_ID INFRA_ORG_ID TOTAL_RECORD` with integration tests we can pull data into automate.


Also getting random error integrations tests failures.
```
infra_service_load_test_data chef-server-dev-test chef-org-dev 100
  hab-studio: Started loading infra service test data...
  hab-studio: Executing Go test
time="2021-03-02T13:00:04Z" level=info msg="running db migrations from \"/src/components/infra-proxy-service/storage/postgres/migration/sql/\""
time="2021-03-02T13:00:04Z" level=info msg="Current schema version: 4 dirty: false"
time="2021-03-02T13:00:04Z" level=info msg="Completed db migrations"
--- FAIL: TestGetEnvironments (23.68s)
    --- FAIL: TestGetEnvironments/Environments_list_with_a_valid_query_search_param (1.55s)
        environments_test.go:98: 
            	Error Trace:	environments_test.go:98
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 2
            	Test:       	TestGetEnvironments/Environments_list_with_a_valid_query_search_param
--- FAIL: TestGetRoles (27.93s)
    --- FAIL: TestGetRoles/Roles_list_with_a_valid_query_search_param (1.56s)
        roles_test.go:101: 
            	Error Trace:	roles_test.go:101
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	TestGetRoles/Roles_list_with_a_valid_query_search_param
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 890 [running]:
testing.tRunner.func1.1(0xdb3240, 0xc00060f5e0)
	/hab/pkgs/core/go/1.14/20200403110524/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000186360)
	/hab/pkgs/core/go/1.14/20200403110524/src/testing/testing.go:944 +0x3f9
panic(0xdb3240, 0xc00060f5e0)
	/hab/pkgs/core/go/1.14/20200403110524/src/runtime/panic.go:967 +0x15d
github.com/chef/automate/components/infra-proxy-service/integration_test_test.TestGetRoles.func6(0xc000186360)
	/src/components/infra-proxy-service/integration_test/roles_test.go:102 +0x2c2
testing.tRunner(0xc000186360, 0xc0003ca340)
	/hab/pkgs/core/go/1.14/20200403110524/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/hab/pkgs/core/go/1.14/20200403110524/src/testing/testing.go:1043 +0x357
FAIL	github.com/chef/automate/components/infra-proxy-service/integration_test	129.863s
FAIL


```

**Comment by vsingh-msys** [comment]
> Integration tests for infra-proxy-service could be another way of loading the data set.

PR has been raised to #4785 adding data using integrations test other approaches nice to consider for better data import.
