### ISSUE TITLE
Failed to upload Compliance Zip file

### ISSUE THREAD

**Issue by kalroy** [chef/automate#5261]
## Describe the bug
Trying to upload the profile zip file failed with error:
```
rpc error: code = Internal desc = InSpec archive failed for /hab/svc/compliance-service/var/tmp/inspec-upload082493173 with message: exit status 1
/hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-core-4.24.32/lib/inspec/utils/json_profile_summary.rb:30:in `write': Permission denied @ rb_sysopen - /hab/svc/compliance-service/var/tmp/inspec-upload082493173/inspec.json (Errno::EACCES)
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-core-4.24.32/lib/inspec/utils/json_profile_summary.rb:30:in `produce_json'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-core-4.24.32/lib/inspec/profile.rb:497:in `archive'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-core-4.24.32/lib/inspec/cli.rb:193:in `archive'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-core-4.24.32/lib/inspec/base_cli.rb:35:in `start'
	from /hab/pkgs/chef/inspec/4.24.32/20210112215549/lib/gems/inspec-bin-4.24.32/bin/inspec:11:in `<main>'
```
Was able to reproduce in acceptance instance.

## To Reproduce
- Open A2
- Goto Compliance tab and profile
- Click on upload and select a zip file
- The file is not uploaded and there is no error.
- Check the network tab

## Expected behavior
The file is uploaded without any issue

## Versions (please complete the following information):
- OS: [e.g. rhel6]
- Automate Build Number [e.g. 20190701222009]

## Additional context
The corresponding customer bug:
https://github.com/chef/customer-bugs/issues/400

The ticket has a zip file which can be used.

**Comment by rickmarry** [comment]
fixed in pr #6146
