### ISSUE TITLE
Node Manager service crashes when calling /nodes/id/{id}

### ISSUE THREAD

**Issue by trickyearlobe** [chef/automate#943]
## Describe the bug

When querying node data via API `GET /nodes/id/{id}` as documented in Swagger at `https://$AUTOMATE_FQDN/api/v0/openapi/ui/#/NodesService/Read`

* using a valid node id (guid), the nodemanager-service crashes and restarts.
* using an invalid id, I get the expected 404 Not Found

## To Reproduce

Get a list of valid node ID's

```
curl -s -H "api-token: $AUTOMATE_TOKEN" -H "Content-Type: application/json" -XPOST https://$AUTOMATE_FQDN/api/v0/nodes/search |jq
```

Assuming a node ID of eea7d742-9db9-49bb-800b-49f9d6aad47

```
curl -s -H "api-token: $AUTOMATE_TOKEN" -H "Content-Type: application/json" -XGET https://$AUTOMATE_FQDN/api/v0/nodes/id/eea7d742-9db9-49bb-800b-49f9d6aad47
```

## Expected behavior

Expected to get a JSON document with some data about the node

## Stack Trace

```
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: authz-service.default(O): time="2019-07-18T07:54:23Z" level=info msg="Authorization Query" action=read resource="nodes:eea7d742-9db9-49bb-800b-49f9d6aad47a" result=true subject="[token:531a569b-3b1b-4ccc-b12f-56e08918ca92]"
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:23Z" level=info msg="read node with : id:\"eea7d742-9db9-49bb-800b-49f9d6aad47a\" "
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): panic: runtime error: invalid memory address or nil pointer dereference
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): [signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0xa35592]
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): goroutine 77 [running]:
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/components/nodemanager-service/api/nodes/server.resolveInspecConfigWithSecrets(0x0, 0x282d5f8, 0x0, 0x0, 0x0, 0x1994a00)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/components/nodemanager-service/api/nodes/server/server.go:198 +0xb12
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/components/nodemanager-service/api/nodes/server.GetNode(0x1992ec0, 0xc00044cae0, 0xc00034fd70, 0xc00000e048, 0x1994a00, 0xc000434100, 0x409d73, 0x158c5c0, 0x165c6e0)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/components/nodemanager-service/api/nodes/server/server.go:132 +0x16c
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/components/nodemanager-service/api/nodes/server.(*Server).Read(0xc0004d83a0, 0x1992ec0, 0xc00044cae0, 0xc00034fd70, 0xc0004d83a0, 0x14adea0, 0x282d5f8)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/components/nodemanager-service/api/nodes/server/server.go:113 +0xc8
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/components/nodemanager-service/api/nodes._NodesService_Read_Handler.func1(0x1992ec0, 0xc00044cae0, 0x162bb40, 0xc00034fd70, 0x16ebfc0, 0xc0002ae000, 0x1992ec0, 0xc00044cae0)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/components/nodemanager-service/api/nodes/nodes.pb.go:1510 +0x86
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1992ec0, 0xc00034f650, 0x162bb40, 0xc00034fd70, 0xc00042c4e0, 0xc00042c500, 0x0, 0x0, 0x0, 0x0)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/components/nodemanager-service/api/nodes._NodesService_Read_Handler(0x165c6e0, 0xc0004d83a0, 0x1992ec0, 0xc00034f650, 0xc00042e3c0, 0xc0004d8340, 0x1992ec0, 0xc00034f650, 0xc000036090, 0x26)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/components/nodemanager-service/api/nodes/nodes.pb.go:1512 +0x158
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046af00, 0x199da00, 0xc00046ac00, 0xc0002a2000, 0xc00044c600, 0x27ff1f8, 0x0, 0x0, 0x0)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/vendor/google.golang.org/grpc/server.go:998 +0x470
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00046af00, 0x199da00, 0xc00046ac00, 0xc0002a2000, 0x0)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/vendor/google.golang.org/grpc/server.go:1278 +0xda6
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): github.com/chef/automate/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000224920, 0xc00046af00, 0x199da00, 0xc00046ac00, 0xc0002a2000)
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/vendor/google.golang.org/grpc/server.go:717 +0x9f
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): created by github.com/chef/automate/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O):         /hab/cache/src/scaffolding-go-gopath/src/github.com/chef/automate/vendor/google.golang.org/grpc/server.go:715 +0xa1
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=info msg="transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"" system=system
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=warning msg="finished unary call with code Unavailable" auth.action=read auth.resource="nodes:eea7d742-9db9-49bb-800b-49f9d6aad47a" auth.subjects="[token:531a569b-3b1b-4ccc-b12f-56e08918ca92]" error="rpc error: code = Unavailable desc = transport is closing" grpc.code=Unavailable grpc.method=Read grpc.service=chef.automate.api.nodes.v1.NodesService grpc.start_time="2019-07-18T07:54:23Z" grpc.time_ms=11.775 iam.version=iam_v1 peer.address="127.0.0.1:54940" span.kind=server system=grpc
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0003cd720, TRANSIENT_FAILURE" system=system
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0003cd720, CONNECTING" system=system
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=info msg="grpc: addrConn.createTransport failed to connect to {172.31.5.8:10120 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.31.5.8:10120: connect: connection refused\". Reconnecting..." system=system
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:23Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0003cd720, TRANSIENT_FAILURE" system=system
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-load-balancer.default(O): - [18/Jul/2019:07:54:23 +0000]  "GET /api/v0//nodes/id/eea7d742-9db9-49bb-800b-49f9d6aad47a HTTP/1.1" 503 "0.013" 99 "-" "automate-cli 0.1.1" "172.31.5.8:2000" "503" "0.012" 401
Jul 18 07:54:23 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: hab-launch(SV): Child for service 'nodemanager-service.default' with PID 27295 exited with code exit code: 2
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(SV): Starting service as user=hab, group=hab
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-pg-gateway.default(O): 172.31.5.8:38074 [18/Jul/2019:07:54:24.201] postgresql automate_postgresql/172.31.5.8 1/0/11 3760 SD 13/13/12/12/0 0/0
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): Migrated nodemanager service tables from chef_compliance_service
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: pg-sidecar-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Removing password for nodemanager" action=create_db conn_info="postgresql://automate@172.31.5.8:10145/<database>?sslmode=verify-ca&sslcert=/hab/svc/automate-postgresql/config/server.crt&sslkey=/hab/svc/automate-postgresql/config/server.key&sslrootcert=/hab/svc/automate-postgresql/config/root.crt" db=nodemanager_service db_database=postgres role=nodemanager user=automate
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: pg-sidecar-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Database exists. Asserting correct owner" action=create_db conn_info="postgresql://automate@172.31.5.8:10145/<database>?sslmode=verify-ca&sslcert=/hab/svc/automate-postgresql/config/server.crt&sslkey=/hab/svc/automate-postgresql/config/server.key&sslrootcert=/hab/svc/automate-postgresql/config/root.crt" db=nodemanager_service db_database=postgres role=nodemanager user=automate
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: pg-sidecar-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="created database" action=create_db conn_info="postgresql://automate@172.31.5.8:10145/<database>?sslmode=verify-ca&sslcert=/hab/svc/automate-postgresql/config/server.crt&sslkey=/hab/svc/automate-postgresql/config/server.key&sslrootcert=/hab/svc/automate-postgresql/config/root.crt" db=nodemanager_service db_database=postgres role=nodemanager user=automate
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-pg-gateway.default(O): 172.31.5.8:38080 [18/Jul/2019:07:54:24.224] postgresql automate_postgresql/172.31.5.8 1/0/109 3806 SD 14/14/13/13/0 0/0
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-pg-gateway.default(O): 172.31.5.8:38084 [18/Jul/2019:07:54:24.238] postgresql automate_postgresql/172.31.5.8 1/0/95 3644 SD 13/13/12/12/0 0/0
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="starting nodemanager service on: 0.0.0.0:10120"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="getting db connection"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Running db migrations from \"/hab/svc/nodemanager-service/static\""
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Current schema version: 5"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Completed db migrations"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Starting nodemanager gRPC Server" uri="0.0.0.0:10120"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="nodemanager setup, dialing secrets-service(172.31.5.8:10131)"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="nodemanager setup, getting an automate-event service client 172.31.5.8:10132"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: nodemanager-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="checking for existence of manual nodemanager"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: authz-service.default(O): time="2019-07-18T07:54:24Z" level=info msg="Authorization Query" action=read resource="ingest:status" result=true subject="[token:chef-server]"
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-load-balancer.default(O): - [18/Jul/2019:07:54:24 +0000]  "GET /data-collector/v0/ HTTP/1.1" 200 "0.003" 15 "-" "-" "172.31.5.8:2000" "200" "0.004" 314
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:24Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0003cd720, CONNECTING" system=system
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-pg-gateway.default(O): 172.31.5.8:37862 [18/Jul/2019:07:53:30.435] postgresql automate_postgresql/172.31.5.8 1/0/54432 4276 sD 14/14/13/13/0 0/0
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-pg-gateway.default(O): 172.31.5.8:37858 [18/Jul/2019:07:53:30.415] postgresql automate_postgresql/172.31.5.8 1/0/54453 5329 sD 13/13/12/12/0 0/0
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-postgresql.default(O): 2019-07-18 07:54:24 GMT [27329]: [1-1] user=nodemanager,db=nodemanager_service,client=172.31.5.8 172.31.5.8(50926) (0:08006)LOG:  could not receive data from client: Connection reset by peer
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-postgresql.default(O): 2019-07-18 07:54:24 GMT [27328]: [1-1] user=nodemanager,db=nodemanager_service,client=172.31.5.8 172.31.5.8(50922) (0:08006)LOG:  could not receive data from client: Connection reset by peer
Jul 18 07:54:24 ip-172-31-5-8.eu-west-2.compute.internal hab[9230]: automate-gateway.default(O): time="2019-07-18T07:54:24Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0003cd720, READY" system=system
^C
[root@ip-172-31-5-8 ~]#
```

## Versions (please complete the following information):
- OS: CentOS7, 16GB (6GB free), 4 vCPU
- Automate Build Number 20190711110747
- chef/nodemanager-service/1.0.0/20190711103650

**Comment by vjeffrey** [comment]
Sorry it's taken me so long to respond here, i completely missed this issue when it came in. i've got a fix up for review: thank you for including the stacktrace. I knew exactly what was happening in under a minute thanks to that stacktrace!
